// TODO
//  - COMPLETE THE CIRCLE BACKGROUND (Completed)
//  - CREATE BUTTON LAYOUT (Completed)
//  - CREATE BUTTON SLIDER (Optional)
//  - ADD LOGO (Completed)
//  - CREATE RANDOM MAP PAGE (In-Progress)
//      -PREVIEW PAGE?
//  - CREATE MANUAL MAP PAGE, SELECTOR (In-Progress)
//      -PREVIEW PAGE/MAKER
